# 不加载，只做展示
server:
  host: "127.0.0.1"
  port: 7860
  project_name: "AgentChat"
  version: "2.0.1"

# 根据自己的MySQL配置更改：mysql+pymysql://账号（root）:账号密码（123456）@主机地址（localhost）:端口号（3306）/数据库名
mysql:
  endpoint: "mysql+pymysql://root:mingguang@localhost:3306/agentchat"

redis:
  endpoint: "redis://localhost:6379"

# 根据自己的LLM配置进行更改
multi_models:
  conversation_model:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model_name: "qwen-plus"
  tool_call_model:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model_name: "qwen-plus"
  reasoning_model:
    api_key: "sk-*****************"
    base_url: "https://api.deepseek.com/v1"
    model_name: "deepseek-reasoner"
  text2image:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis"
    model_name: "wanx2.0-t2i-turbo"
  qwen_vl:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model_name: "qwen-vl-plus"

  # 根据自己的Embedding配置进行更改
  embedding:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model_name: "text-embedding-v4"

  # 根据自己的Rerank配置进行更改
  rerank:
    api_key: "sk-****************"
    base_url: "https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank"
    model_name: "gte-rerank-v2"


tools:
  # 使用高德地图上的天气api
  weather:
    api_key: "fac0ad465***********"
    endpoint: "https://restapi.amap.com/v3/weather/weatherInfo?parameters"

  # 使用的tavily上的联网搜索功能， 1000次/month
  tavily:
    api_key: "tvly-dev-**************"

  # 使用的是serpapi上的Google Search的api
  google:
    api_key: "cdc3b20760684****************"

  # 使用的是aliyun上的快递查询api
  delivery:
    api_key: "df69*****************"
    endpoint: "https://qyexpress.market.alicloudapi.com/composite/queryexpress"

rag:
  enable_summary: False # 是否对片段进行摘要

  retrival:
    top_k: 5  # 知识库召回的数量
    min_score: 0.2 # 知识库召回的最小分数

  split:
    chunk_size: 500 # 知识库片段的最大字符数
    overlap_size: 100 # 知识库片段之间的重复字符

  elasticsearch:
    hosts: "http://127.0.0.1:9200"

  # vector db根据自己的配置更改
  vector_db:
    host: "127.0.0.1"
    port: "19530"
    mode: "chroma" # standalone 代表完整功能的Milvus; lite是轻量版的Milvus; chroma是更轻量级的向量库，mode 选择 chroma 不需要填host和 port


aliyun_oss:
  access_key_id: "LTAI5tL85xWWx9*********"
  access_key_secret: "MiKCkLCx9qZzxc*******"
  endpoint: "oss-cn-beijing.aliyuncs.com"
  bucket_name: "agentchat"
  base_url: "https://agentchat.oss-cn-beijing.aliyuncs.com"

logo: # 创建
  tool_url: "https://agentchat.oss-cn-beijing.aliyuncs.com/icons/tool.png"
  agent_url: "https://agentchat.oss-cn-beijing.aliyuncs.com/icons/tools/bot.png"

mars:
  daily_url: "https://news.aibase.com/zh/news"

memory:
  collection_name: "memory"

whitelist_paths: ["/login"] #, "/api/v1"]

# 目前版本不应用
langfuse:
  trace_name: "FunctionCallChat"
  host: "https://cloud.langfuse.com"
  public_key:
  secret_key:
  user_id: "tian_chat"